# Generated by Django 5.2.5 on 2025-08-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idade',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='link',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
